---
title: "Belper Knolle"
author: "Gavin Webber"
format: 
  revealjs:
    incremental: false
---

## Ingredients

::: {style="font-size:0.7em"}

- 4L full cream pasteuirzed milk
- 1/8 t of Flora Danica (aromatic mesophilic culture) or Sacco MO36R
- 0.75ml  (1/8 t) calcium chloride in 1/4 cup non-chlorinated water
- 6 drops single strength linquid rennet in 1 T of non-chlorinated water (standard dose?)
- 3 T kosher salt
- 3 cloves garlic
- 3 T black peppercorns
- cheese box
- colander
- tight weave cheese cloth (for hanging)
- loose weave cheese cloth (for keeping off insects)
- large bowl for whey
- large bowl for mixing in salt
- rope to hang with

:::

## if using a tablet rennet, dissolve it in the water

## remove starter culture from freezer

## Put milk on the heat

- target is 30C

## whisk / stir the cream through the milk

## Add calcium chloride

- 0.75ml in 1/4 cup

## Heat milk to 30C

## Sprinkle over freeze dried starter culture

## wait 5 mins

## stir in the starter culture

- can use kefir? try a few T

## add rennet and stir for 1 mins

## cover and let set for 12-18 hours

- it is ready when the curds come away from the edge of the pot and there is a thin layer of whey on top of the curds.

## line a colander with cheese cloth and ladel the curds into it

## tie the cheese cloth together and hang over a pot

## hang for 18 hours

## move the cheese to a bowl

## break the cheese apart

- check for firmness

## add to mortar and pestle:

- 3 garlic cloves chopped
- 1.5t of salt

## grind to a smooth paste

## mix the paste through the cheese

## add salt to taste

- 0.5 t at a time

## put in the fridge and set a timer for 30mins

- this is to help it firm up

## wash and dry pestle and mortar

## toast the peppercorns until they change colour

- should take around 2 mins

## add to mortar and pestel and grind to medium fine

## after 30 mins, shape the cheese into 5 even balls

- slightly smaller than the size of a tennise ball

## get a cheese box and bamboo mat sterilised and ready to go

## put the pepper on a dinner plate

- start with half so you can more evenly distribute the pepper

## roll the cheese balls in the pepper and place in the cheese box

## cover the cheese box with cheese cloth

- put near a fan to help air flow

## air dry at room temp for 2 days

- turn every 6 hours
- they will get lighter in colour
- may take less in hot weather

## put into cheese cave

- add silica gell to keep the environment drier

## leave for 4-6 weeks?

## resources

- [https://www.youtube.com/watch?v=-tuSxGcK1GI](How to make)
- [https://www.youtube.com/watch?v=AGo0746S1X8&t=301s](after aging)
