---
title: "Cantal"
author: "Cole Dawson (Cheese It!)"
format: revealjs
---

## Ingredients

Yield: 2 pounds

::: {style="font-size:0.7em"}

- 9L full cream pasteuirzed milk
- 1/4 t of Mesophilic Culture, or 4 T mesophilic mother culture
- 2.5ml  (1/2 t) liquid rennet in 1/4 cup non-chlorinated water (or 1/4 rennet table)
- 2 T kosher salt
- cheese mold
- cheese cloth
- cheese box
- colander
- large bowl for whey
- large bowl for mixing in salt
- weights

:::

## Heat milk to (30C)

- 1/4 t of Mesophilic Culture, or 4 T mesophilic mother culture
- prepare 2.5ml  (1/2 t) liquid rennet in 1/4 cup non-chlorinated water

## Sprinkle on mesophilic culture, leave for 2 mins

## Stir, cover, and ripen for 15 mins at 30C

## Add rennet and stir for 1 minute

## Cover, and keep at 30C for 1 hour or until clean break

## Cut curds into 1/4 inch cubes

- Use a wisk to cut pieces you miss

## Let sit (covered) for 5 mins

## Pour curds and whey through a cheese cloth lined colander

- keep warm while it drain (about 20 mins)

## Break curds into several pieces and put into a cheese basket lined with cheese cloth

## Press at 2.4-4.5kg for 12 hours

## Flip and press for 12 more hours

- at same weight (2.4-4.5kg).

## In a large bowl, mill (break up) the cheese into 1-inch pieces.

## Add 2 T kosher salt and mix well

- knead with your fingers

## Rinse the mold and cloth

## Place the cheese in the mold lined with cloth

## Press at 10-20kg for 2-3 days

- flipping every day

## Remove and let air-try at room temp for 2-3 days

- flipping every 6 hours

## When dry to touch

- Age at 10-13C and 80-85%RH for 3-6 months.
- flip the cheese and wipe the rind with brine twice a week
