---
title: "Gouda"
author: "Gavin Webber"
format: 
  revealjs:
    incremental: false
---

## Ingredients

- 10L full cream milk
- 1/8th t (dash) of Mesophilic Culture (MO30)
- 2.5ml (1/2 t) calcium chloride in 1/4 cup non-chlorinated water
- 2.5ml  (1/2 t) liquid rennet in 1/4 cup non-chlorinated water
- Saturated Brine Solution
  - calcium chloride
  - salt
- cheese wax or vacumme bag
- ladle
- container for whey
- seive
- bamboo mat for drying

## Put milk on the heat (29C)

- measure 1/8th t (dash) of Mesophilic Culture (MO30)
- prepare 2.5ml  (1/2 t) calcium chloride in 1/4 cup non-chlorinated water
- prepare 2.5ml  (1/2 t) liquid rennet in 1/4 cup non-chlorinated water

## Add mesophilic culture

- also add a little kifir

## Let it sit for a couple mins then stir in

## Stir calcium chloride

- If using unpasturised milk
- 2.5ml (1/2 t) calcium chloride in 1/4 cup non-chlorinated water

## Add rennet

- 2.5ml  (1/2 t) liquid rennet in 1/4 cup non-chlorinated water
- stir no more than 1min

## Let sit until clean break (30-40 mins)

- mine took 1h15mins

## Cut curds into half inch cubes

## Let sit (covered) for 5 mins

- prepare some non-chlorinated water at 60C, at least 3L.

## Stir for 5 mins

## Let sit for 5 mins

- prepare some non-chlorinated water at 60C, at least 3L.

## Using a sieve, ladle out 4 cups (1L) of whey

- sieve keeps the curds out of the cup.

## Replace 4 cups of 60C water

- target temp is 33C.

## Stir gently for 10 mins

## Let settle for 5-10 mins

- reduce temp of water to 45C.

## Note the level of the whey

- there may be a level of curds on the side of the pot.

## Ladle out the whey to the level of the curds

## Stir, then add 45C water to the level that the whey was

- temperature should be 37C

## Stir for 20 mins

- do we maintain temperature? I think yes

## Let rest for 10 mins

## Drain out the whey, putting the curds into a cheese cloth lined mold

## Press at 10kg for 30 mins

## Flip and press at 13kg for 12 hours

## Put into brine for 12 hours

- flip the cheese half way through
- can trim off any weird bits first

## Air dry on bamboo cheese mat for 2-3 days until touch dry

- turn at least every day

## vacuum seal

## mature at 10-12C for at least 6 weeks

