---
title: "Gruyere"
author: "Gavin Webber - https://youtu.be/Oi2y4Ymrd5A"
format: 
  revealjs:
    incremental: false
---

# Ingredients

- 10L full cream milk (3.4-4.1% milk fat)
- 1/4 teaspoon (tad) thermophilic culture (MOT92)
- 2.5ml (1/2 t) calcium chloride in 1/4 cup non-chlorinated water
- 2.5ml (1/2 t) liquid rennet (200 IMCU) in 1/4 cup non-chlorinated water 
- saturated brine solution

# Heat milk to 32C

# Sprinkle thermophilic culture on top

# Leave for 5 mins

# Stir for a couple mins

- make sure milk is still at 32C

# Let sit for 10 mins

# Add calcium chloride

# Add rennet and stir for 1 min

# Rest covered for 40 mins

# Check for clean break

- rest another 10 mins if not clean

# Cut curds to 1cm pieces (or pea sized curd cubes)

# Stir for 1 hour

- slowly heat the milk up to 46C.

# Let the curds settle for 5 mins

- line a 165mm cheese mold with loose weave cheese cloth and place it inside a colander in a bowl (if you want to reserve the whey)

# Pour whey through the mold

# Put follower on curds and pull cheese cloth to get out wrinkles

# Press at 11kg (22lb) for 1 hour

# Flip the cheese

- redress the cheese with the cheese cloth when you do this

# Press at 22kg for 12 hours

# Place in saturated brine solution for 10 hours

- flip once
- if cheese floats, sprinkle 1t on top of the cheese

# Remove from brine, pat dry and place on drying rack

- can also trim any defects with a knife

# Air dry cheese for 2-3 days until touch dry

- cover with cheeese cloth to stop insects.

# Place in ripening box

- 13C
- 90-95% rh

# Flip and wash with brine twice per week

# After 1 month, flip and wash weekly

- set a calendar event for 1 month

# After 2 months, turn weekly and brush with soft dry cloth

- or brush with a soft nail brush

- Age to around 6 months

# See also notes from [tasting video]()

