---
title: "Gouda"
author: "David Asher (modification by looking at the Gavin Webber recipe)"
format: 
  revealjs:
    incremental: false
---

## Ingredients

- 8L full cream milk
- culture:
  - 1/8th t (dash) of Thermophilic Culture
  - or 90ml active kefir
- 2ml (1/4 t) calcium chloride in 60ml cup non-chlorinated water
- double dose of rennet
- salt
- wire whisk
- ladle
- container for whey
- colander
- bamboo mat for drying

## Ingredients (3L version)

- 3L full creatm non-homogenised milke
- or 40ml active kefir
- 0.75ml calcium chloride in 30ml cup non-chlorinated water
- double dose of rennet
- salt
- wire whisk
- ladle
- container for whey
- colander
- bamboo mat for drying

## remove freezer Ingredients

## heat milk to 32C

- dissolve rennet tablets in water (double dose according to packet)
- prepare calcium chloride (2ml in 60ml, or 0.78 in 30ml for 3L)

## add culture

- sprinkle culture on top of milk and let stand for 5 mins
- mix the kefir (or yoghurt) with some of the milk, then mix into all of it

## stir in the culture

## stir in calcium chloride

- 2ml in 60ml water
- or, 0.75ml in 60ml for 3L

## add rennet and stir for 1 minutes

## cover and set for 1 hour at 32C

## Stir in rennet for 1 minute

## incubate for 1 hour

- or until clean break

## cut the curds to size of lentil

- wisk like crazy with a wire whisk for 1-2 mins
- stir the curds to check that there are no large pieces

## cook the curds to 43C while stiring
 
- do this for 30-60 mins, or,
- until they bounce back when pressed between fingers

## allow curds to settle for 5 mins

## pour off the whey

- save 1L for washing brine

## put the curds into cheese basket

-- press lightly (5kg?) for 5 mins

## make the washing brine

- 1T (15ml) salt in 1L of warm whey
- refrigerate

## flip the cheese, rewrap and press a little harder

- do this every 10 mins for the next hour

## let air dry overnight

## surface salt the cheese

- 1T (15ml) for 4L of milk (Asher)
- 2t (10ml) for 8L of salt on the top
  - stand at room temp for 24 hours  
  - flip and thing rub in another 2t on the other side
  - stand at room temp for another 24 hours

## air dry flipping every so often until there is no visible moisture

## place in cheese cave

- 16C, 85% RH

# wash the rind every other day for 1 week.

# flip weekly as it ages for at least 6 weeks (at least 6 months is better)

- can also vacuum pack at some point to avoid moulds and reduce maintenance
